
/**
 * Configuración de Prisma para el proyecto.
 * Define la ubicación del esquema, migraciones y conexión a la base de datos.
 * Archivo generado por Prisma.
 */

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma", // Ubicación del esquema de base de datos
  migrations: {
    path: "prisma/migrations", // Directorio de migraciones
  },
  engine: "classic", // Motor de Prisma a usar
  datasource: {
    url: env("DATABASE_URL"), // URL de conexión desde variables de entorno
  },
});
